title: "Aden's Portfolio"
description: "A portfolio to showcase my projects and achievements."

theme: Portfolio  # Use 'minima' or another Jekyll theme
author: Aden Athar
paginate: 5

# Optional social links
social_links:
  - github: https://github.com/<your-username>
  - linkedin: https://linkedin.com/in/<your-linkedin-profile>
